name: Deploy React Application
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t thanhlep/reactjs-web --build-arg VITE_API_ROOT=${{ secrets.VITE_API_ROOT }} --build-arg VITE_SOCKET_URL=${{ secrets.VITE_SOCKET_URL }} --build-arg VITE_ADMIN_ID=${{ secrets.VITE_ADMIN_ID }} --build-arg VITE_GOOGLE_MAP_API_KEY=${{ secrets.VITE_GOOGLE_MAP_API_KEY }} --build-arg VITE_DOMAIN_AUTH0=${{ secrets.VITE_DOMAIN_AUTH0 }} --build-arg VITE_CLIENT_ID_AUTH0=${{ secrets.VITE_CLIENT_ID_AUTH0 }} --build-arg VITE_REACT_GOOGLE_CLIENT_ID=${{ secrets.VITE_REACT_GOOGLE_CLIENT_ID }} --build-arg VITE_FACEBOOK_APP_ID=${{ secrets.VITE_FACEBOOK_APP_ID }} .
      - name: Publish Image to docker hub
        run: docker push thanhlep/reactjs-web:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull thanhlep/reactjs-web:latest
      - name: Delete old container
        run: docker rm -f reactjs-web-container
      - name: Run Docker Container
        run: docker run -d -p 5173:80 --name reactjs-web-container thanhlep/reactjs-web
